#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    55 < length and do {
            s/.{40}\K.*//;
            s/ \S*$|$/... <Read More>/;
        };
    $_
} split "\n"
