#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    eval '0b' . join '',
    map {
        my ($flag, $len) = map length, split ' ';
        scalar (
        1 < $flag ?
                1
            :
                0
        ) x $len
    } m/0+ 0+/g
} split "\n"
