#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my @A = split //;
	my @B = (0) x @A;
	map {
		$B[ $_ ] ++
	} @A;
	0 + (@B ~~ @A);
} split "\n";

print "\n"
