#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my ($x, $y, $X, $Y) = split;
	$_ = q(SNWE);
	my $re;
	$re = qw(WE E W)[$x - $X <=> 0];
	s/$re//;
	$re = qw(SN N S)[$y - $Y <=> 0];
	s/$re//;
	$_ ||= 'here';
} split "\n";

print "\n"
