#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my %h;
	my $c = map $h{ $_ } ++, split /,/;
	my $maxC = (sort {$b <=> $a} values %h)[ 0 ];
	my $value = join '', grep $h{ $_ } == $maxC, keys %h;
	$maxC > $c / 2 ?
		$value
	:
		'None'
} split "\n";

print "\n"
