#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    $_ = join '', split;
    my $n = sqrt length;
    
    my @new;    

    for my $i (0 .. -1 + length){
        $new[ $n - 1 - $i % $n ] .= chop
    }

    join ' ', split '', join '', @new
    
} split "\n"
