#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    my ($deg, $rem) = split /\./;

    sprintf "$deg.%02d'%02d\"",
    map {
        (
        int "0.$rem" * 60,
        $rem = (split /\./, "0.$rem" * 60)[1] || 0,
        )[0]
    } 0 .. 1
} split "\n"

