#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    join ' ',
    map {
        substr $_, 1, (-2 + length),
        reverse
        substr $_, 1, (-2 + length);
        scalar
        reverse
    } split ' '
} split "\n"
