#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    my ($text, $indexes) = split /;/;
    
    my @text = split ' ', $text;
    my @indexes = map $_ - 1, split ' ', $indexes; 
    my @new_text;

    map {
        $new_text[ shift @indexes ] = shift @text
    } 0 .. @indexes - 1;

    my $i = 0;
    while (1){
        defined $new_text[ $i ] or 
            $new_text[ $i ] = shift @text
            and last;
        $i ++;
    }

    join ' ',  @new_text
    
} split "\n"
