#!/usr/bin/perl

use warnings;
use strict;

my $arrows = join '', map "(?:$_)", join '|', <DATA> =~ m/[-<>]+/g;

{ local $/ ; $_ = <> };

print join "\n",
map {
	scalar( () = m/(?=$arrows)/g)
} split "\n";

print "\n"

__DATA__
An arrow is a set of the following symbols: '>>-->' or '<--<<'. 
