#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my @mult;
	map {
		my $i = 0;
		map {
			defined $mult[ $i ] or $mult[ $i ] = 1;
			$mult[ $i ++ ] *= $_
		} split
	} split /\|/;
	join ' ', @mult
} split "\n";

print "\n"
