#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
    my ($num, $two) = split /,/;
	my $i = 1;
	0 while $two * $i ++ < $num;
	$two *-- $i
} split "\n";

print "\n"
