#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

my $data;
{ local $/; $data = <DATA> };

my %morse = map { reverse map s/·/./gr, split } $data =~ m/\b \w \s+ [-·]+/xg;

print join "\n",
map {
    s/[-.]+/$morse{ $& }/xgr =~ s/ \b//gr
} split "\n";

print "\n";

__DATA__
Lotyniškos abėcėlės raidės

Žemiau pateikiamoje kodo lentelėje simbolio nuoroda veda į garso įrašą, skambantį perduodant šį simbolį Morzės abėcėle.
Raidė 	Kodas 	Raidė 	Kodas
A 	·- 	N 	-·
B 	-··· 	O 	---
C 	-·-· 	P 	·--·
D 	-·· 	Q 	--·-
E 	· 	R 	·-·
F 	··-· 	S 	···
G 	--· 	T 	-
H 	···· 	U 	··-
I 	·· 	V 	···-
J 	·--- 	W 	·--
K 	-·- 	X 	-··-
L 	·-·· 	Y 	-·--
M 	-- 	Z 	--··
Skaitmenys

Žemiau pateikiamoje kodo lentelėje skaitmens nuoroda veda į garso įrašą, skambantį perduodant šį skaitmenį Morzės abėcėle.
Skaitmuo 	Kodas
0 	-----
1 	·----
2 	··---
3 	···--
4 	····-
5 	·····
6 	-····
7 	--···
8 	---··
9 	----·
