#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print map "$_\n",
map {
    map {
        my $i = 0;
        join ' ',
        map {
            '*' x $i ++ . $_
        } split //
    } (sort {length $b <=> length $a} split ' ')[0]
} split "\n"
