#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my ($num, $a, $b) = split /,/;
	$num = reverse sprintf "%030b", $num;
	qw(false true)[ eval join '==', map { substr $num, $_ -1, 1 } $a, $b ]
} split "\n";

print "\n"
