#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my ($fst, $sec) = split /;/;
	my %fst = map { $_, 1 } split /,/, $fst;
	join ',', grep $fst{ $_ }, split /,/, $sec
} split "\n";

print "\n"
