#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my $R = 'IV XL CD M? ?';
	join '', reverse
	map {
		$R =~ m/(\S)(\S)(?= (\S))/g;
		my ($one, $five, $ten) = ($1, $2, $3);
		do {
			if (0) { ; }
			elsif (/[1-3]/){ $one x $& }
			elsif (/[6-8]/){ $five . $one x ($& - 5) }
			elsif (/4/){ $one . $five }
			elsif (/9/){ $one . $ten }
			elsif (/5/){ $five }
			elsif (/0/){ '' }
		}
	} reverse split //
} split "\n";

print "\n"
