#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my ($F, $B, $len) = split;
	my @arr = 1 .. $len;
	join ' ',
	map {
		$_ .= join '',
		($_ % $F ? '' : 'F'),
		($_ % $B ? '' : 'B');
		m/[FB]/ ? s/\d+//r : $_;
	} @arr
} split "\n";

print "\n"
