#!/usr/bin/perl

use warnings;
use strict;

{ local $/ ; $_ = <> };

print join "\n",
map {
	my $len = length;
	qw(False True)[
		0 + eval join '==', $_, eval join '+',
		map {
			$_ ** $len
		} split //
	]
} split "\n";

print "\n"
